name: Workflow CI - Retrain Model with MLflow Project


on:
  push:
    branches: [main]
    paths:
      - "MLProject/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch: {}

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (sesuai MLProject/conda.yaml)
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.22.5 pandas==2.3.3 scikit-learn==1.8.0 numpy==2.2.6


      - name: Run MLflow Project (retrain model)
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

     
      - name: Upload trained model as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-${{ github.run_number }}
          path: MLProject/model
          retention-days: 30

      - name: Upload MLflow tracking metadata (mlruns) as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-${{ github.run_number }}
          path: MLProject/mlruns
          retention-days: 30

      - name: Tag and push Docker image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/flower-species-classifier:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/flower-species-classifier:${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flower-species-classifier:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flower-species-classifier:${{ github.run_number }}
